# UK Train Rides Dataset - Data Preprocessing

This notebook focuses on preparing the cleaned dataset for analysis by creating new features and improving data usability.

In [1]:
import pandas as pd

df = pd.read_csv("railway_cleaned.csv")

In [32]:
df["Date of Purchase"] = pd.to_datetime(df["Date of Purchase"])
df["Date of Journey"] = pd.to_datetime(df["Date of Journey"])

df["Time of Purchase"] = pd.to_datetime(
    df["Time of Purchase"],
    format="mixed"
)

df["Departure Time"] = pd.to_datetime(
    df["Departure Time"],
    format="mixed"
)

df["Arrival Time"] = pd.to_datetime(
    df["Arrival Time"],
    format="mixed"
)

df["Actual Arrival Time"] = pd.to_datetime(
    df["Actual Arrival Time"],
    format="mixed",
    errors="coerce"
)

In [33]:
df.head()

,Transaction ID,Date of Purchase,Time of Purchase,Purchase Type,Payment Method,Railcard,Ticket Class,Ticket Type,Price,Departure Station,...,Purchase Year,Purchase Month,Purchase Month Name,Purchase Day,Has Railcard,Is Delayed,Purchase Hour,Departure Hour,Arrival Hour,Journey Duration
0,da8a6ba8-b3dc-4677-b176,2023-12-08,1900-01-01 12:41:11,Online,Contactless,Adult,Standard,Advance,43,London Paddington,...,2023,12,December,Friday,Yes,No,12,11,13,150.0
1,b0cdd1b0-f214-4197-be53,2023-12-16,1900-01-01 11:23:01,Station,Credit Card,Adult,Standard,Advance,23,London Kings Cross,...,2023,12,December,Saturday,Yes,Yes,11,9,11,110.0
2,f3ba7a96-f713-40d9-9629,2023-12-19,1900-01-01 19:51:27,Online,Credit Card,No Railcard,Standard,Advance,3,Liverpool Lime Street,...,2023,12,December,Tuesday,No,No,19,18,18,30.0
3,b2471f11-4fe7-4c87-8ab4,2023-12-20,1900-01-01 23:00:36,Station,Credit Card,No Railcard,Standard,Advance,13,London Paddington,...,2023,12,December,Wednesday,No,No,23,21,22,60.0
4,2be00b45-0762-485e-a7a3,2023-12-27,1900-01-01 18:22:56,Online,Contactless,No Railcard,Standard,Advance,76,Liverpool Lime Street,...,2023,12,December,Wednesday,No,No,18,16,19,135.0

In [34]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 31653 entries, 0 to 31652
Data columns (total 28 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Transaction ID       31653 non-null  str
 1   Date of Purchase     31653 non-null  datetime64[us]
 2   Time of Purchase     31653 non-null  datetime64[us]
 3   Purchase Type        31653 non-null  str
 4   Payment Method       31653 non-null  str
 5   Railcard             31653 non-null  str
 6   Ticket Class         31653 non-null  str
 7   Ticket Type          31653 non-null  str
 8   Price                31653 non-null  int64
 9   Departure Station    31653 non-null  str
 10  Arrival Destination  31653 non-null  str
 11  Date of Journey      31653 non-null  datetime64[us]
 12  Departure Time       31653 non-null  datetime64[us]
 13  Arrival Time         31653 non-null  datetime64[us]
 14  Actual Arrival Time  29773 non-null  datetime64[us]
 15  Journey Status       31653 non-null  str
 16  Reason for Delay     4172 non-null   str
 17  Refund Request       31653 non-null  str
 18  Purchase Year        31653 non-null  int32
 19  Purchase Month       31653 non-null  int32
 20  Purchase Month Name  31653 non-null  str
 21  Purchase Day         31653 non-null  str
 22  Has Railcard         31653 non-null  str
 23  Is Delayed           31653 non-null  str
 24  Purchase Hour        31653 non-null  int32
 25  Departure Hour       31653 non-null  int32
 26  Arrival Hour         31653 non-null  int32
 27  Journey Duration     31653 non-null  float64
dtypes: datetime64[us](6), float64(1), int32(5), int64(1), str(15)
memory usage: 6.2 MB

In [35]:
df["Date of Purchase"] = pd.to_datetime(df["Date of Purchase"])
df["Date of Journey"] = pd.to_datetime(df["Date of Journey"])

df["Purchase Year"] = df["Date of Purchase"].dt.year

In [36]:
df["Purchase Month"] = df["Date of Purchase"].dt.month

In [37]:
df["Purchase Month Name"] = df["Date of Purchase"].dt.month_name()

In [38]:
df["Purchase Day"] = df["Date of Purchase"].dt.day_name()

In [39]:
df.head()

,Transaction ID,Date of Purchase,Time of Purchase,Purchase Type,Payment Method,Railcard,Ticket Class,Ticket Type,Price,Departure Station,...,Purchase Year,Purchase Month,Purchase Month Name,Purchase Day,Has Railcard,Is Delayed,Purchase Hour,Departure Hour,Arrival Hour,Journey Duration
0,da8a6ba8-b3dc-4677-b176,2023-12-08,1900-01-01 12:41:11,Online,Contactless,Adult,Standard,Advance,43,London Paddington,...,2023,12,December,Friday,Yes,No,12,11,13,150.0
1,b0cdd1b0-f214-4197-be53,2023-12-16,1900-01-01 11:23:01,Station,Credit Card,Adult,Standard,Advance,23,London Kings Cross,...,2023,12,December,Saturday,Yes,Yes,11,9,11,110.0
2,f3ba7a96-f713-40d9-9629,2023-12-19,1900-01-01 19:51:27,Online,Credit Card,No Railcard,Standard,Advance,3,Liverpool Lime Street,...,2023,12,December,Tuesday,No,No,19,18,18,30.0
3,b2471f11-4fe7-4c87-8ab4,2023-12-20,1900-01-01 23:00:36,Station,Credit Card,No Railcard,Standard,Advance,13,London Paddington,...,2023,12,December,Wednesday,No,No,23,21,22,60.0
4,2be00b45-0762-485e-a7a3,2023-12-27,1900-01-01 18:22:56,Online,Contactless,No Railcard,Standard,Advance,76,Liverpool Lime Street,...,2023,12,December,Wednesday,No,No,18,16,19,135.0

In [40]:
df["Has Railcard"] = df["Railcard"].apply(
    lambda x: "Yes" if x != "No Railcard" else "No"
)

In [41]:
df["Has Railcard"].value_counts()

Has Railcard
No     20918
Yes    10735
Name: count, dtype: int64

In [42]:
df["Is Delayed"] = df["Journey Status"].apply(
    lambda x: "Yes" if x == "Delayed" else "No"
)

In [43]:
df["Is Delayed"].value_counts()

Is Delayed
No     29361
Yes     2292
Name: count, dtype: int64

In [44]:
df["Time of Purchase"] = pd.to_datetime(
    df["Time of Purchase"],
    errors="coerce"
)

df["Departure Time"] = pd.to_datetime(
    df["Departure Time"],
    errors="coerce"
)

df["Arrival Time"] = pd.to_datetime(
    df["Arrival Time"],
    errors="coerce"
)

df["Actual Arrival Time"] = pd.to_datetime(
    df["Actual Arrival Time"],
    errors="coerce"
)

In [45]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 31653 entries, 0 to 31652
Data columns (total 28 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Transaction ID       31653 non-null  str
 1   Date of Purchase     31653 non-null  datetime64[us]
 2   Time of Purchase     31653 non-null  datetime64[us]
 3   Purchase Type        31653 non-null  str
 4   Payment Method       31653 non-null  str
 5   Railcard             31653 non-null  str
 6   Ticket Class         31653 non-null  str
 7   Ticket Type          31653 non-null  str
 8   Price                31653 non-null  int64
 9   Departure Station    31653 non-null  str
 10  Arrival Destination  31653 non-null  str
 11  Date of Journey      31653 non-null  datetime64[us]
 12  Departure Time       31653 non-null  datetime64[us]
 13  Arrival Time         31653 non-null  datetime64[us]
 14  Actual Arrival Time  29773 non-null  datetime64[us]
 15  Journey Status       31653 non-null  str
 16  Reason for Delay     4172 non-null   str
 17  Refund Request       31653 non-null  str
 18  Purchase Year        31653 non-null  int32
 19  Purchase Month       31653 non-null  int32
 20  Purchase Month Name  31653 non-null  str
 21  Purchase Day         31653 non-null  str
 22  Has Railcard         31653 non-null  str
 23  Is Delayed           31653 non-null  str
 24  Purchase Hour        31653 non-null  int32
 25  Departure Hour       31653 non-null  int32
 26  Arrival Hour         31653 non-null  int32
 27  Journey Duration     31653 non-null  float64
dtypes: datetime64[us](6), float64(1), int32(5), int64(1), str(15)
memory usage: 6.2 MB

In [47]:
df["Purchase Hour"] = df["Time of Purchase"].dt.hour

df["Departure Hour"] = df["Departure Time"].dt.hour

df["Arrival Hour"] = df["Arrival Time"].dt.hour

In [48]:
df["Journey Duration"] = (
    df["Arrival Time"] -
    df["Departure Time"]
).dt.total_seconds() / 60

df.loc[
    df["Journey Duration"] < 0,
    "Journey Duration"
] += 1440

In [49]:
df["Journey Duration"].describe()

count    31653.000000
mean        71.154235
std         36.330811
min         15.000000
25%         30.000000
50%         80.000000
75%         90.000000
max        270.000000
Name: Journey Duration, dtype: float64

In [50]:
negative_duration = df[df["Journey Duration"] < 0]

negative_duration.shape

(0, 28)

In [51]:
df["Journey Duration"].describe()

count    31653.000000
mean        71.154235
std         36.330811
min         15.000000
25%         30.000000
50%         80.000000
75%         90.000000
max        270.000000
Name: Journey Duration, dtype: float64

In [52]:
df[
    [
        "Departure Time",
        "Arrival Time",
        "Journey Duration"
    ]
].sample(10)

           Departure Time        Arrival Time  Journey Duration
19614 1900-01-01 17:15:00 1900-01-01 19:05:00             110.0
26375 1900-01-01 07:30:00 1900-01-01 08:40:00              70.0
272   1900-01-01 15:30:00 1900-01-01 16:50:00              80.0
19292 1900-01-01 09:45:00 1900-01-01 11:05:00              80.0
10757 1900-01-01 08:15:00 1900-01-01 09:35:00              80.0
27984 1900-01-01 20:00:00 1900-01-01 21:00:00              60.0
11823 1900-01-01 06:30:00 1900-01-01 07:50:00              80.0
30071 1900-01-01 17:45:00 1900-01-01 19:05:00              80.0
12437 1900-01-01 17:30:00 1900-01-01 19:45:00             135.0
14840 1900-01-01 17:45:00 1900-01-01 19:05:00              80.0

In [54]:
df.to_csv(
    "railway_preprocessed.csv",
    index=False
)

## Preprocessing Summary

- Extracted purchase year and month features.
- Created month name feature.
- Created weekday feature.
- Created Has Railcard feature.
- Created Is Delayed feature.
- Extracted purchase, departure, and arrival hours.
- Created Journey Duration feature.
- Fixed overnight journeys causing negative durations.
- Saved the preprocessed dataset.